# Generated by Django 5.0.6 on 2024-05-30 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artista')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDisco',
            fields=[
                ('id_detalle_disco', models.AutoField(primary_key=True, serialize=False)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artista')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInstrumento',
            fields=[
                ('id_detalle_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id_disco', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('detalle_disco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.detalledisco')),
            ],
        ),
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('id_genero_musical', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('detalle_instrumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.detalleinstrumento')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disco')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='SelloDiscografico',
            fields=[
                ('id_sello_discografico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id_tipo_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='cancion',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disco'),
        ),
        migrations.AddField(
            model_name='detalledisco',
            name='genero_musical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generomusical'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero_musical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generomusical'),
        ),
        migrations.AddField(
            model_name='detalleinstrumento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marca'),
        ),
        migrations.AddField(
            model_name='detalledisco',
            name='sello_discografico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sellodiscografico'),
        ),
        migrations.AddField(
            model_name='detalleinstrumento',
            name='tipo_instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoinstrumento'),
        ),
    ]
